name: build release

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    if: github.actor == 'Kiriyaga7615'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [1.21.5, 1.21.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ matrix.branch }}

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build client
        run: ./gradlew clean build remapJar --stacktrace

      - name: List files in build/libs
        run: ls -l build/libs/

      - name: Set safe branch name
        run: |
          SAFE_BRANCH="${{ matrix.branch }}"
          SAFE_BRANCH="${SAFE_BRANCH//./-}"
          echo "SAFE_BRANCH=$SAFE_BRANCH" >> $GITHUB_ENV

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: nami-${{ env.SAFE_BRANCH }}
          path: build/libs/*.jar

  release:
    needs: build
    if: github.actor == 'Kiriyaga7615'
    runs-on: ubuntu-latest
    steps:
      - name: Set version for release
        run: |
          SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
          echo "VERSION=multi-branch-latest-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Download all branch artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifact

      - name: List downloaded files
        run: ls -l ./artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Nami ${{ env.VERSION }}
          body: |
            Combined release for branches: 1.21.5 and 1.21.8
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload all JARs to Release
        run: |
          for file in ./artifact/*.jar; do
            echo "Uploading $file to release tag ${{ env.VERSION }}"
            gh release upload ${{ env.VERSION }} "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
