name: build release

on:
  workflow_dispatch:

jobs:
  build:
    if: github.actor == 'Kiriyaga7615'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build client
        run: ./gradlew clean build remapJar --stacktrace

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: nami-client
          path: build/libs/*-remapped.jar

  release:
    needs: build
    if: github.actor == 'Kiriyaga7615'
    runs-on: ubuntu-latest

    steps:
      - name: artifact
        uses: actions/download-artifact@v4
        with:
          name: nami-client

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 420.28
          name: Nami 420.28
          body: |
            First release!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        run: |
          JAR_FILE=$(ls *.jar | head -n 1)
         echo "Uploading $JAR_FILE to release tag 420.28"
          gh release upload 420.28 "$JAR_FILE" --clobber
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
