name: build release

on:
  workflow_dispatch:

jobs:
  build:
    if: github.actor == 'Kiriyaga7615'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build client
        run: ./gradlew clean build remapJar --stacktrace

      - name: List files in build/libs
        run: ls -l build/libs/

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: nami-client
          path: build/libs/*.jar

  release:
    needs: build
    if: github.actor == 'Kiriyaga7615'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nami-client
          path: ./artifact

      - name: List downloaded files
        run: ls -l ./artifact

      - name: Set version from short commit SHA
        run: echo "VERSION=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Nami ${{ env.VERSION }}
          body: |
            First release!
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload JAR to Release
        run: |
          JAR_FILE=$(ls ./artifact/*.jar | head -n 1)
          echo "Uploading $JAR_FILE to release tag ${{ env.VERSION }}"
          gh release upload ${{ env.VERSION }} "$JAR_FILE" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
